# pull official base image
FROM node:alpine

# set working directory
WORKDIR /app

# install app dependencies
COPY ./react-app/package*.json ./
RUN npm install

# add app/or mount volume
COPY ./react-app ./
# default react port to expose
EXPOSE 3000
# start app
CMD ["npm", "run", "start"]